# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount/discount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discount/discount.proto',
  package='protocols',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x64iscount/discount.proto\x12\tprotocols\"4\n\x12VerifyDiscountForm\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0e\n\x06prodid\x18\x02 \x01(\t\"3\n\x0c\x44iscountInfo\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x03\x32V\n\x08\x44iscount\x12J\n\x0eVerifyDiscount\x12\x1d.protocols.VerifyDiscountForm\x1a\x17.protocols.DiscountInfo\"\x00\x62\x06proto3')
)




_VERIFYDISCOUNTFORM = _descriptor.Descriptor(
  name='VerifyDiscountForm',
  full_name='protocols.VerifyDiscountForm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='protocols.VerifyDiscountForm.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prodid', full_name='protocols.VerifyDiscountForm.prodid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=90,
)


_DISCOUNTINFO = _descriptor.Descriptor(
  name='DiscountInfo',
  full_name='protocols.DiscountInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='protocols.DiscountInfo.pct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='protocols.DiscountInfo.value_in_cents', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['VerifyDiscountForm'] = _VERIFYDISCOUNTFORM
DESCRIPTOR.message_types_by_name['DiscountInfo'] = _DISCOUNTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyDiscountForm = _reflection.GeneratedProtocolMessageType('VerifyDiscountForm', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYDISCOUNTFORM,
  '__module__' : 'discount.discount_pb2'
  # @@protoc_insertion_point(class_scope:protocols.VerifyDiscountForm)
  })
_sym_db.RegisterMessage(VerifyDiscountForm)

DiscountInfo = _reflection.GeneratedProtocolMessageType('DiscountInfo', (_message.Message,), {
  'DESCRIPTOR' : _DISCOUNTINFO,
  '__module__' : 'discount.discount_pb2'
  # @@protoc_insertion_point(class_scope:protocols.DiscountInfo)
  })
_sym_db.RegisterMessage(DiscountInfo)



_DISCOUNT = _descriptor.ServiceDescriptor(
  name='Discount',
  full_name='protocols.Discount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=145,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='VerifyDiscount',
    full_name='protocols.Discount.VerifyDiscount',
    index=0,
    containing_service=None,
    input_type=_VERIFYDISCOUNTFORM,
    output_type=_DISCOUNTINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNT)

DESCRIPTOR.services_by_name['Discount'] = _DISCOUNT

# @@protoc_insertion_point(module_scope)
